

# This file was *autogenerated* from the file TPM.sage
from sage.all_cmdline import *   # import sage library

_sage_const_256 = Integer(256)
from domain import Domain
class TPM:
	def __init__(self, domain: Domain):
		self.domain = domain
		# 公开参数
		self.a_t = self.domain.OK.random_element()
		# tpm的私钥
		self.e_t = self.domain.OK.random_element()

		# 基名和基名的秘密值
		self.bsn = None
		self.sk = None
	
	def mutiple_e_t(self, val):
		return self.e_t * val
	
	def join_request(self):
		return self.a_t * self.e_t

	def sign_request(self):
		if self.bsn is None:
			self.bsn = self.domain.OK.random_element()
		if self.sk is None:
			self.sk = self.domain.OK.random_element(_sage_const_256 )
		
		d = hash(self.bsn)  # 基名摘要
		e_n = hash((self.sk, self.bsn))  # 秘密值和基名摘要

		nym = d * self.e_t + e_n  # 伪名
		return d, e_n, nym, self.bsn

